#!/usr/bin/env python3
"""
tech_blog_writer_final - CrewAI Project

AI-orchestrated crew for: Create a simple blog writer who can write informative blog posts about technology topics

Generated by agentforge on 2025-09-21 16:01:37
"""

import sys
from .crew import TechBlogWriterFinalCrew


def main():
    """Main entry point for the crew."""
    # Get task input from command line arguments
    if len(sys.argv) > 1:
        task_input = " ".join(sys.argv[1:])
        print(f"  Command line arguments: {sys.argv[1:]}")
        print(f"[INFO] Task input: {task_input}")
    else:
        task_input = "Create a simple blog writer who can write informative blog posts about technology topics"
        print(f"[INFO] No command line arguments provided, using default task")
    
    # Initialize and run the crew
    print(f"[INFO] Initializing TechBlogWriterFinalCrew crew...")
    crew = TechBlogWriterFinalCrew()
    result = crew.run(task_input)
    
    print("\n" + "="*50)
    print("CREW EXECUTION COMPLETED")
    print("="*50)
    print(result)
    
    return result


if __name__ == "__main__":
    main()
